name: Sync to Customer Repo (Post-PR Merge Only)
 
on:
  push:
    branches:
      - main
 
jobs:
  mirror:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
 
    - name: Configure Git
      run: |
        git config --global user.name "saravanan014"
        git config --global user.email "saravanan014@users.noreply.github.com"
 
    - name: Add customer repo remote
      env:
        TOKEN: ${{ secrets.TARGET_PAT }}
      run: |
        git remote add customer https://saravanan014:$TOKEN@github.com/revendh/cust_test.git
 
    - name: Push main branch to customer repo
      run: |
        git push customer main
 
